// File generated by FlutterFire CLI.
// PLACEHOLDER — Replace with real config by running:
//   flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAuiJsA9sVMb76hC4a2CtMYYlTDwkSGBk',
    appId: '1:179190872224:web:a93092dbb2a861d68031c5',
    messagingSenderId: '179190872224',
    projectId: 'refsure-28a67',
    authDomain: 'refsure-28a67.firebaseapp.com',
    storageBucket: 'refsure-28a67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyGtUlhYZz86cMiSvH0BpElvAgw7BKWSw',
    appId: '1:179190872224:android:f619f8bcb74f373f8031c5',
    messagingSenderId: '179190872224',
    projectId: 'refsure-28a67',
    storageBucket: 'refsure-28a67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFDlhGAQDhy9t0rSFL7p2Q6FDB6MQwps',
    appId: '1:179190872224:ios:6cbe0be78cb4fe848031c5',
    messagingSenderId: '179190872224',
    projectId: 'refsure-28a67',
    storageBucket: 'refsure-28a67.firebasestorage.app',
    iosBundleId: 'com.refsure.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAFDlhGAQDhy9t0rSFL7p2Q6FDB6MQwps',
    appId: '1:179190872224:ios:6cbe0be78cb4fe848031c5',
    messagingSenderId: '179190872224',
    projectId: 'refsure-28a67',
    storageBucket: 'refsure-28a67.firebasestorage.app',
    iosBundleId: 'com.refsure.app',
  );

}